image: docker:latest

stages:
    - build
    - deploy

services:
    - docker:dind

variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"

pages:
    stage: deploy
    image: node
    cache:
        paths:
            - node_modules/
    script:
        - npm install
        - npm run build
        - rm -rf public
        - cp build/index.html build/404.html
        - mv build public
    artifacts:
        paths:
            - public
    only:
        - main

build-latest:
    stage: build
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker pull node:lts
        - docker pull $CI_REGISTRY_IMAGE:builder-latest || true
        - docker build --target builder --cache-from node:lts,$CI_REGISTRY_IMAGE:builder-latest --tag $CI_REGISTRY_IMAGE:builder-latest --build-arg REACT_APP_WEBAPI_URL=http://35.238.73.104:8008 --build-arg PUBLIC_URL=/ .
        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - docker build --cache-from node:lts,$CI_REGISTRY_IMAGE:builder-latest --cache-from node:lts,$CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest --build-arg REACT_APP_WEBAPI_URL=http://35.238.73.104:8008 --build-arg PUBLIC_URL=/ .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:builder-latest
    only:
        - main

build-production:
    stage: build
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker pull node:lts
        - docker pull $CI_REGISTRY_IMAGE:builder-prod || true
        - docker build --target builder --cache-from node:lts,$CI_REGISTRY_IMAGE:builder-prod --tag $CI_REGISTRY_IMAGE:builder-prod --build-arg REACT_APP_WEBAPI_URL=https://service-pro-balance.nambaone.app --build-arg PUBLIC_URL=/ .
        - docker pull $CI_REGISTRY_IMAGE:production || true
        - docker build --cache-from node:lts,$CI_REGISTRY_IMAGE:builder-prod --cache-from node:lts,$CI_REGISTRY_IMAGE:production --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:production --build-arg REACT_APP_WEBAPI_URL=https://service-pro-balance.nambaone.app --build-arg PUBLIC_URL=/ .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:production
        - docker push $CI_REGISTRY_IMAGE:builder-prod
    only:
        - production
